# Generated by Django 5.2.13 on 2026-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period', models.DateField(verbose_name='last menstrual period')),
                ('expected_delivery_date', models.DateField(editable=False, verbose_name='expected delivery date')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10, verbose_name='risk level')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='patients.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'pregnancy record',
                'verbose_name_plural': 'pregnancy records',
                'ordering': ['-last_menstrual_period'],
            },
        ),
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='visit date')),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='blood pressure (systolic)')),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='blood pressure (diastolic)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('symptoms_noted', models.TextField(blank=True, verbose_name='symptoms noted')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_visits', to='maternal.pregnancyrecord', verbose_name='pregnancy')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_prenatal_visits', to='accounts.healthworker', verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'prenatal visit',
                'verbose_name_plural': 'prenatal visits',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pregnancyrecord',
            index=models.Index(fields=['patient', 'is_active'], name='maternal_pr_patient_252742_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancyrecord',
            index=models.Index(fields=['expected_delivery_date'], name='maternal_pr_expecte_e5b002_idx'),
        ),
        migrations.AddIndex(
            model_name='prenatalvisit',
            index=models.Index(fields=['pregnancy', 'date'], name='maternal_pr_pregnan_3f359d_idx'),
        ),
        migrations.AddIndex(
            model_name='prenatalvisit',
            index=models.Index(fields=['recorded_by', 'date'], name='maternal_pr_recorde_225d0b_idx'),
        ),
    ]
