# Generated by Django 5.2.13 on 2026-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='protocol name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'symptom protocol',
                'verbose_name_plural': 'symptom protocols',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='symptom name')),
                ('severity_weight', models.IntegerField(verbose_name='severity weight')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='triage.symptomprotocol', verbose_name='protocol')),
            ],
            options={
                'verbose_name': 'symptom',
                'verbose_name_plural': 'symptoms',
                'ordering': ['protocol', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TriageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(verbose_name='minimum score')),
                ('max_score', models.IntegerField(verbose_name='maximum score')),
                ('recommendation', models.CharField(choices=[('URGENT', 'Urgent referral'), ('TREATMENT', 'Basic treatment'), ('MONITOR', 'Monitoring')], max_length=20, verbose_name='recommendation')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('next_steps', models.TextField(verbose_name='next steps')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_rules', to='triage.symptomprotocol', verbose_name='protocol')),
            ],
            options={
                'verbose_name': 'triage rule',
                'verbose_name_plural': 'triage rules',
                'ordering': ['protocol', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='score')),
                ('recommendation_given', models.CharField(choices=[('URGENT', 'Urgent referral'), ('TREATMENT', 'Basic treatment'), ('MONITOR', 'Monitoring')], max_length=20, verbose_name='recommendation given')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to='patients.patient', verbose_name='patient')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_checks', to='accounts.healthworker', verbose_name='performed by')),
                ('symptoms_selected', models.ManyToManyField(related_name='symptom_checks', to='triage.symptom', verbose_name='symptoms selected')),
            ],
            options={
                'verbose_name': 'symptom check',
                'verbose_name_plural': 'symptom checks',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['patient', 'date'], name='triage_symp_patient_d4ad25_idx'), models.Index(fields=['performed_by', 'date'], name='triage_symp_perform_647c2c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['protocol', 'is_active'], name='triage_symp_protoco_26a0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='triagerule',
            index=models.Index(fields=['protocol', 'min_score', 'max_score'], name='triage_tria_protoco_02d2fa_idx'),
        ),
    ]
