# Generated by Django 5.2.13 on 2026-04-10 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maternal', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MISSED_VISIT', 'Missed visit'), ('DANGER_SIGN', 'Danger sign'), ('HIGH_RISK', 'High risk')], max_length=20, verbose_name='alert type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='severity')),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('related_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient', verbose_name='related patient')),
                ('related_pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maternal.pregnancyrecord', verbose_name='related pregnancy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', 'severity', 'created_at'], name='alerts_aler_resolve_3d030c_idx'), models.Index(fields=['related_patient', 'created_at'], name='alerts_aler_related_e54625_idx')],
            },
        ),
    ]
