#!/usr/bin/env python3
"""Regenerate locale/fr/LC_MESSAGES/django.po with French msgstr (no Django required)."""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "locale" / "fr" / "LC_MESSAGES" / "django.po"

# (msgid, msgstr) — msgid must match Python/templates exactly.
PAIRS: list[tuple[str, str]] = [
    # --- Accounts / admin ---
    ("Health Worker Information", "Fiche agent de santé"),
    ("Community Health Worker", "Agent de santé communautaire"),
    ("District Supervisor", "Superviseur de district"),
    ("System Administrator", "Administrateur système"),
    ("role", "rôle"),
    ("phone number", "numéro de téléphone"),
    ("English", "Anglais"),
    ("French", "Français"),
    ("preferred language", "langue préférée"),
    ("user", "utilisateur"),
    ("users", "utilisateurs"),
    ("district name", "nom du district"),
    ("region", "région"),
    ("supervisor", "superviseur"),
    ("district", "district"),
    ("districts", "districts"),
    ("contact phone", "téléphone de contact"),
    ("active", "actif"),
    ("health worker", "agent de santé"),
    ("health workers", "agents de santé"),
    # --- Alerts ---
    ("Missed visit", "Visite manquée"),
    ("Danger sign", "Signe de danger"),
    ("High risk", "Risque élevé"),
    ("Low", "Faible"),
    ("Medium", "Modéré"),
    ("High", "Élevé"),
    ("Critical", "Critique"),
    ("alert type", "type d'alerte"),
    ("related patient", "patient concerné"),
    ("related pregnancy", "grossesse concernée"),
    ("severity", "gravité"),
    ("resolved", "résolu"),
    ("resolved by", "résolu par"),
    ("resolved at", "résolu le"),
    ("created at", "créé le"),
    ("notes", "notes"),
    ("alert", "alerte"),
    ("alerts", "alertes"),
    ("%(type)s, %(patient)s", "%(type)s, %(patient)s"),
    # --- Maternal ---
    ("patient", "patient"),
    ("last menstrual period", "dernières règles"),
    ("expected delivery date", "date prévue d'accouchement"),
    ("risk level", "niveau de risque"),
    ("pregnancy record", "dossier de grossesse"),
    ("pregnancy records", "dossiers de grossesse"),
    ("Pregnancy for %(patient)s (EDD %(edd)s)", "Grossesse — %(patient)s (DPA %(edd)s)"),
    ("LMP is required.", "Les dernières règles sont obligatoires."),
    ("pregnancy", "grossesse"),
    ("visit date", "date de visite"),
    ("blood pressure (systolic)", "tension artérielle (systolique)"),
    ("blood pressure (diastolic)", "tension artérielle (diastolique)"),
    ("weight (kg)", "poids (kg)"),
    ("symptoms noted", "symptômes notés"),
    ("recorded by", "enregistré par"),
    ("prenatal visit", "visite prénatale"),
    ("prenatal visits", "visites prénatales"),
    ("Visit on %(date)s, %(patient)s", "Visite du %(date)s — %(patient)s"),
    # --- Patients ---
    ("Female", "Féminin"),
    ("Male", "Masculin"),
    ("Other / prefer not to say", "Autre / préfère ne pas répondre"),
    ("first name", "prénom"),
    ("last name", "nom"),
    ("age", "âge"),
    ("sex", "sexe"),
    ("village", "village"),
    ("assigned CHW", "ASC référent"),
    ("patients", "patients"),
    # --- Triage ---
    ("protocol name", "nom du protocole"),
    ("description", "description"),
    ("version", "version"),
    ("symptom protocol", "protocole de symptômes"),
    ("symptom protocols", "protocoles de symptômes"),
    ("protocol", "protocole"),
    ("symptom name", "nom du symptôme"),
    ("severity weight", "pondération de gravité"),
    ("category", "catégorie"),
    ("symptom", "symptôme"),
    ("symptoms", "symptômes"),
    ("Urgent referral", "Orientation urgente"),
    ("Basic treatment", "Traitement de base"),
    ("Monitoring", "Surveillance"),
    ("minimum score", "score minimum"),
    ("maximum score", "score maximum"),
    ("recommendation", "recommandation"),
    ("explanation", "explication"),
    ("next steps", "prochaines étapes"),
    ("triage rule", "règle de triage"),
    ("triage rules", "règles de triage"),
    (
        "%(rec)s for %(protocol)s (scores %(min)s to %(max)s)",
        "%(rec)s — %(protocol)s (scores %(min)s à %(max)s)",
    ),
    ("Minimum score cannot exceed maximum score.", "Le score minimum ne peut pas dépasser le score maximum."),
    ("symptoms selected", "symptômes sélectionnés"),
    ("score", "score"),
    ("recommendation given", "recommandation donnée"),
    ("date", "date"),
    ("performed by", "réalisé par"),
    ("symptom check", "session de triage"),
    ("symptom checks", "sessions de triage"),
    ("Check for %(patient)s on %(date)s", "Triage pour %(patient)s le %(date)s"),
    # --- Forms (patients) ---
    ("Assigned CHW", "ASC assigné"),
    ("First name", "Prénom"),
    ("Last name", "Nom"),
    ("Age", "Âge"),
    ("Sex", "Sexe"),
    ("Village", "Village"),
    ("Invalid assignee.", "Assignation invalide."),
    (
        "You cannot assign a patient to this health worker.",
        "Vous ne pouvez pas assigner ce patient à cet agent.",
    ),
    # --- Forms (maternal) ---
    ("Patient", "Patient"),
    ("Last menstrual period", "Dernières règles"),
    ("Risk level", "Niveau de risque"),
    ("Active pregnancy", "Grossesse active"),
    ("You cannot open a pregnancy for this patient.", "Vous ne pouvez pas ouvrir une grossesse pour ce patient."),
    ("Recorded by", "Enregistré par"),
    ("Visit date", "Date de visite"),
    ("Systolic BP", "TA systolique"),
    ("Diastolic BP", "TA diastolique"),
    ("Weight (kg)", "Poids (kg)"),
    ("Symptoms noted", "Symptômes notés"),
    ("Notes", "Notes"),
    ("Invalid recorder.", "Enregistreur invalide."),
    (
        "You cannot attribute this visit to that health worker.",
        "Vous ne pouvez pas attribuer cette visite à cet agent.",
    ),
    # --- Views / messages ---
    ("You do not have permission to register or edit patients.", "Vous n'avez pas l'autorisation d'enregistrer ou de modifier des patients."),
    ("Patient saved.", "Patient enregistré."),
    ("Patient updated.", "Patient mis à jour."),
    ("You cannot resolve this alert.", "Vous ne pouvez pas résoudre cette alerte."),
    ("Already resolved.", "Déjà résolu."),
    ("Alert marked resolved.", "Alerte marquée comme résolue."),
    (
        "You do not have permission to add or change pregnancy records.",
        "Vous n'avez pas l'autorisation d'ajouter ou de modifier des grossesses.",
    ),
    ("New pregnancy", "Nouvelle grossesse"),
    ("Pregnancy record saved.", "Grossesse enregistrée."),
    ("Edit pregnancy", "Modifier la grossesse"),
    ("Pregnancy record updated.", "Grossesse mise à jour."),
    ("Prenatal visit saved.", "Visite prénatale enregistrée."),
    (
        "Triage checks must be saved under a community health worker profile. Ask an administrator to link your account.",
        "Les sessions de triage doivent être enregistrées sous un profil d'agent de santé. Demandez à un administrateur de lier votre compte.",
    ),
    ("General", "Général"),
    ("Triage saved.", "Triage enregistré."),
    (
        "You do not have permission to download reports.",
        "Vous n'avez pas l'autorisation de télécharger les rapports.",
    ),
    # --- API ---
    ("Active community health worker profile required.", "Un profil d'agent de santé actif est requis."),
    ("Patient not found.", "Patient introuvable."),
    ("Protocol not found.", "Protocole introuvable."),
    ("Protocol has no rules configured.", "Aucune règle n'est configurée pour ce protocole."),
    ("No matching rule.", "Aucune règle ne correspond."),
    # --- Triage service ---
    (
        "No triage rule matches this score. Ask an administrator to review protocol bands.",
        "Aucune règle ne correspond à ce score. Demandez à un administrateur de vérifier les bandes du protocole.",
    ),
    # --- SMS ---
    (
        "CommuniSanté: %(type)s — %(patient)s (%(sev)s).",
        "CommuniSanté : %(type)s — %(patient)s (%(sev)s).",
    ),
    # --- Reporting (CSV/PDF) ---
    ("District", "District"),
    ("CHW", "ASC"),
    ("Village", "Village"),
    ("Sex", "Sexe"),
    ("Age", "Âge"),
    ("Active pregnancies", "Grossesses actives"),
    ("Open alerts", "Alertes ouvertes"),
    ("Registered", "Enregistré"),
    ("High-risk pregnancies (active register)", "Grossesses à haut risque (registre actif)"),
    ("LMP", "DDR"),
    ("EDD", "DPA"),
    ("Risk", "Risque"),
    ("No high-risk pregnancies in this scope.", "Aucune grossesse à haut risque dans ce périmètre."),
    # --- Templates: base & core ---
    ("CommuniSanté", "CommuniSanté"),
    ("Admin", "Administration"),
    ("Language", "Langue"),
    ("OK", "OK"),
    ("Community health platform — offline-first", "Plateforme de santé communautaire — pensée hors ligne"),
    ("Community health platform, offline first", "Plateforme de santé communautaire, pensée pour le hors-ligne"),
    (
        "Lightweight tools for community health workers in rural West Africa.",
        "Des outils légers pour les agents de santé communautaires en Afrique de l'Ouest rurale.",
    ),
    ("Open admin", "Ouvrir l'administration"),
    ("Staff admin", "Administration du personnel"),
    ("Dashboard", "Tableau de bord"),
    ("My patients", "Mes patients"),
    ("Alerts", "Alertes"),
    ("Symptom triage", "Triage des symptômes"),
    ("Prenatal care", "Suivi prénatal"),
    ("Log in", "Connexion"),
    ("Log out", "Déconnexion"),
    ("Patients", "Patients"),
    ("Triage", "Triage"),
    ("ANC", "CPN"),
    # --- More templates ---
    ("Continue", "Continuer"),
    ("Back to home", "Retour à l'accueil"),
    ("Search", "Rechercher"),
    ("Name or village", "Nom ou village"),
    ("Previous", "Précédent"),
    ("Next", "Suivant"),
    ("No patients yet.", "Aucun patient pour le moment."),
    ("New patient", "Nouveau patient"),
    ("Edit patient", "Modifier le patient"),
    ("Save", "Enregistrer"),
    ("Cancel", "Annuler"),
    ("Pregnancies", "Grossesses"),
    ("New pregnancy", "Nouvelle grossesse"),
    ("Filter", "Filtre"),
    ("All", "Tous"),
    ("Active only", "Actives seulement"),
    ("Closed", "Clôturée"),
    ("EDD", "DPA"),
    ("Risk", "Risque"),
    ("No pregnancy records yet.", "Aucune grossesse enregistrée."),
    ("Pregnancy", "Grossesse"),
    ("Prenatal visit", "Visite prénatale"),
    ("Elevated blood pressure", "Tension artérielle élevée"),
    (
        "Consider urgent assessment or referral according to your district protocol.",
        "Envisagez une évaluation urgente ou une orientation selon le protocole de votre district.",
    ),
    ("Date", "Date"),
    ("Blood pressure", "Tension artérielle"),
    ("not set", "non renseigné"),
    ("Weight", "Poids"),
    ("kg", "kg"),
    ("Symptoms", "Symptômes"),
    ("Back to pregnancy", "Retour à la grossesse"),
    ("Triage checklist", "Liste de triage"),
    ("Get recommendation", "Obtenir la recommandation"),
    ("Back", "Retour"),
    ("Status", "Statut"),
    ("Open", "Ouverte"),
    ("Resolved", "Résolue"),
    ("Severity", "Gravité"),
    ("Type", "Type"),
    ("Apply", "Appliquer"),
    ("Optional note", "Note facultative"),
    ("Mark resolved", "Marquer comme résolu"),
    ("No alerts in this view.", "Aucune alerte dans cette vue."),
    ("Triage result", "Résultat du triage"),
    ("Score", "Score"),
    ("Recommendation", "Recommandation"),
    ("Explanation", "Explication"),
    ("Next steps", "Prochaines étapes"),
    (
        "Protocol text may have changed since this check was saved.",
        "Le protocole a pu changer depuis l'enregistrement de ce triage.",
    ),
    ("Signs ticked", "Signes cochés"),
    ("Patient file", "Dossier patient"),
    ("Another triage", "Autre triage"),
    ("Choose a protocol, then select a patient.", "Choisissez un protocole, puis un patient."),
    (
        "Your account needs an active community health worker profile to save a triage session. Supervisors can still review records in the admin.",
        "Un profil d'agent de santé actif est nécessaire pour enregistrer un triage. Les superviseurs peuvent consulter les dossiers dans l'administration.",
    ),
    (
        "No active protocols yet. Run load_demo_triage or add one in the admin.",
        "Aucun protocole actif. Exécutez load_demo_triage ou ajoutez-en un dans l'administration.",
    ),
    ("Welcome", "Bienvenue"),
    ("Register patient", "Enregistrer un patient"),
    ("Supervisor overview for your districts.", "Vue d'ensemble de vos districts."),
    (
        "No district is linked to your account yet. Ask an administrator to assign you as supervisor on a district.",
        "Aucun district n'est lié à votre compte. Demandez à un administrateur de vous assigner comme superviseur.",
    ),
    ("Patients in scope", "Patients du périmètre"),
    ("Active CHWs", "ASC actifs"),
    ("New patients in the last 7 days", "Nouveaux patients sur 7 jours"),
    ("New patients (7 days)", "Nouveaux patients (7 jours)"),
    ("By district", "Par district"),
    ("CSV", "CSV"),
    ("Export", "Exporter"),
    (
        "Download CSV (district activity)",
        "Télécharger le CSV (activité par district)",
    ),
    (
        "Download PDF (high-risk pregnancies)",
        "Télécharger le PDF (grossesses à haut risque)",
    ),
    ("Download CSV (all patients)", "Télécharger le CSV (tous les patients)"),
    ("Administrator overview.", "Vue d'ensemble administrateur."),
    ("Districts", "Districts"),
    (
        "Admins: add ?district=&lt;id&gt; to the CSV URL to filter one district (IDs from the admin site).",
        "Admins : ajoutez ?district=&lt;id&gt; à l'URL du CSV pour un district (identifiants dans l'admin).",
    ),
    (
        "Your account does not have a dashboard role yet. Use the admin site or ask for a CHW or supervisor profile.",
        "Votre compte n'a pas encore de rôle tableau de bord. Utilisez l'administration ou demandez un profil ASC ou superviseur.",
    ),
    ("Open patient file", "Ouvrir le dossier patient"),
    ("Expected delivery", "Accouchement prévu"),
    ("Active", "Active"),
    ("Edit pregnancy", "Modifier la grossesse"),
    ("Log prenatal visit", "Saisir une visite prénatale"),
    ("Back to list", "Retour à la liste"),
    ("Blood pressure follow up", "Suivi de la tension artérielle"),
    (
        "One or more visits recorded high blood pressure. Arrange referral per local ANC guidelines.",
        "Une ou plusieurs visites ont noté une tension élevée. Organisez une orientation selon les directives locales de CPN.",
    ),
    ("Prenatal visits", "Visites prénatales"),
    ("BP", "TA"),
    ("No visits logged yet.", "Aucune visite enregistrée."),
    ("Edit", "Modifier"),
    ("Run triage", "Lancer le triage"),
    ("Choose patient", "Choisir un patient"),
    ("Choose a patient", "Choisir un patient"),
    (
        "You need an active community health worker profile to open the checklist.",
        "Un profil d'agent de santé actif est nécessaire pour ouvrir la liste.",
    ),
    (
        "No patients available. Register a patient first.",
        "Aucun patient disponible. Enregistrez d'abord un patient.",
    ),
    ("Back to protocols", "Retour aux protocoles"),
    ("closed", "clôturée"),
]


def escape_po(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main() -> None:
    seen: set[str] = set()
    lines = [
        '# CommuniSanté — French translations',
        '# Regenerate: python3 scripts/build_fr_django_po.py',
        '# Then: msgfmt -o locale/fr/LC_MESSAGES/django.mo locale/fr/LC_MESSAGES/django.po',
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: CommuniSanté\\n"',
        '"Report-Msgid-Bugs-To: \\n"',
        '"POT-Creation-Date: 2026-04-11 12:00+0000\\n"',
        '"PO-Revision-Date: 2026-04-11 12:00+0000\\n"',
        '"Last-Translator: CommuniSanté <team@communisante.local>\\n"',
        '"Language-Team: French <fr@li.org>\\n"',
        '"Language: fr\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Plural-Forms: nplurals=2; plural=(n > 1);\\n"',
        "",
    ]
    for msgid, msgstr in PAIRS:
        if msgid in seen:
            continue
        seen.add(msgid)
        lines.append(f'msgid "{escape_po(msgid)}"')
        lines.append(f'msgstr "{escape_po(msgstr)}"')
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(seen)} entries)")


if __name__ == "__main__":
    main()
