# Generated by Django 5.2.13 on 2026-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other / prefer not to say')], max_length=1, verbose_name='sex')),
                ('village', models.CharField(blank=True, max_length=255, verbose_name='village')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('assigned_chw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.healthworker', verbose_name='assigned CHW')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'), models.Index(fields=['assigned_chw', 'created_at'], name='patients_pa_assigne_c8767d_idx')],
            },
        ),
    ]
